image: jangrewe/gitlab-ci-android

stages:
- build

before_script:
- echo systemProp.http.proxyHost=192.168.3.1 >> gradle.properties
- echo systemProp.http.proxyPort=1080 >> gradle.properties
- echo systemProp.https.proxyHost=192.168.3.1 >> gradle.properties
- echo systemProp.https.proxyPort=1080 >> gradle.properties
- echo org.gradle.jvmargs=-Xmx1536m >> gradle.properties
- echo org.gradle.parallel=true >> gradle.properties
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  only:
    - develop
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/app-debug.apk
    expire_in: 3 day
