stages:
- build
- deploy

variables:
  app_location: app/build/outputs/apk/release/app-release.apk

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

release_github:
  dependencies:
  - build
  only:
  - master
  stage: deploy
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog_Android.git HEAD:master
  - bash upload-github-release-asset.sh github_api_token=${github_key} owner=silverblogteam repo=SilverBlog_Android tag=$(date "+%Y%m%d%H%M%S") filename=${app_location} proxy=${proxy}


build:
  image: preventis/docker-android-alpine
  stage: build
  only:
    - develop
  script:
  - echo -e "ext { appVersionCode = ${CI_PIPELINE_ID} }" > ./app/version.gradle
  - echo -e "systemProp.http.proxyHost=192.168.3.8\n systemProp.http.proxyPort=1080\n systemProp.https.proxyHost=192.168.3.8\n systemProp.https.proxyPort=1080\n org.gradle.jvmargs=-Xmx1536m\n org.gradle.parallel=true" >> gradle.properties
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - ./gradlew assembleRelease
  artifacts:
    paths:
    - ${app_location}
    expire_in: 1 week
