image: docker.reallserver.cn/public/gitlab-ci-android:latest

stages:
- build
- deploy

variables:
  app_location: app/build/outputs/apk/release/app-release.apk

before_script:
- echo systemProp.http.proxyHost=192.168.3.8 >> gradle.properties
- echo systemProp.http.proxyPort=1080 >> gradle.properties
- echo systemProp.https.proxyHost=192.168.3.8 >> gradle.properties
- echo systemProp.https.proxyPort=1080 >> gradle.properties
- echo org.gradle.jvmargs=-Xmx1536m >> gradle.properties
- echo org.gradle.parallel=true >> gradle.properties
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

push_to_github:
  only:
  - tags
  stage: deploy
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog_Android.git HEAD:master --tags
  - wget https://gist.githubusercontent.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447/raw/dbadd7d310ce8446de89c4ffdf1db0b400d0f6c3/upload-github-release-asset.sh
  - bash upload-github-release-asset.sh silverblogteam SilverBlog_Android ${CI_COMMIT_TAG} ${app_location} ${github_key}

build:
  stage: build
  script:
  - ./gradlew assembleRelease
  artifacts:
    paths:
    - ${app_location}
    expire_in: 1 week
