image: docker.reallserver.cn/public/gitlab-ci-android:latest

stages:
- build
- deploy

variables:
  app_location: app/build/outputs/apk/release/app-release.apk

before_script:
- echo systemProp.http.proxyHost=192.168.3.8 >> gradle.properties
- echo systemProp.http.proxyPort=1080 >> gradle.properties
- echo systemProp.https.proxyHost=192.168.3.8 >> gradle.properties
- echo systemProp.https.proxyPort=1080 >> gradle.properties
- echo org.gradle.jvmargs=-Xmx1536m >> gradle.properties
- echo org.gradle.parallel=true >> gradle.properties
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

push_to_github:
  dependencies:
  - build
  only:
  - master
  stage: deploy
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog_Android.git HEAD:master --tags
  - commit_log=$(git log --pretty=format:'%s' --abbrev-commit --date=short -1)
  - tag=$(date "+%Y%m%d%H%M%S")
  - bash upload-github-release-asset.sh github_api_token=${github_key} owner=silverblogteam repo=SilverBlog_Android body=${commit_log} tag=${tag} filename=${app_location}

build:
  stage: build
  script:
  - ./gradlew assembleRelease
  artifacts:
    paths:
    - ${app_location}
    expire_in: 1 week
