image: jangrewe/gitlab-ci-android

stages:
- build
- deploy

before_script:
- echo systemProp.http.proxyHost=192.168.3.1 >> gradle.properties
- echo systemProp.http.proxyPort=1080 >> gradle.properties
- echo systemProp.https.proxyHost=192.168.3.1 >> gradle.properties
- echo systemProp.https.proxyPort=1080 >> gradle.properties
- echo org.gradle.jvmargs=-Xmx1536m >> gradle.properties
- echo org.gradle.parallel=true >> gradle.properties
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

push_to_github:
  only:
  - tags
  stage: deploy
  script:
  - git config --global http.proxy "http://192.168.3.1:1080"
  - git config --global https.proxy "http://192.168.3.1:1080"
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog_Android.git HEAD:master --tags

build:
  only:
   - develop
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 1 week
  tags:
    - docker-runner-1