language: android

sudo: false

android:
  components:
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"     
  - chmod +x gradlew
notifications:
  webhooks:https://fathomless-fjord-24024.herokuapp.com/notify
script:
  - echo org.gradle.jvmargs=-Xmx1536m >> gradle.properties
  - echo org.gradle.parallel=true >> gradle.properties
  - ./gradlew assembleRelease
 
before_deploy:

deploy:
  provider: releases
  api_key:
    secure: $Github_token
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true